name: Build and Deploy Docusaurus Site

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        working-directory: website
        run: npm install

      - name: Build Docusaurus Site
        working-directory: website
        run: npm run build

      - name: Checkout Deployment Repository
        uses: actions/checkout@v3
        with:
          repository: nickdebaise/nickdebaise.github.io
          path: deployment-repo
          token: ${{ secrets.GIT_TOKEN }}

      - name: Copy Build to GH Pages
        run: |
          rm -rf deployment-repo/packages/react-native-toast
          mkdir -p deployment-repo/packages/react-native-toast
          cp -R website/build/* deployment-repo/packages/react-native-toast/

      - name: Commit and Push
        run: |
          cd deployment-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/react-native-toast
          git commit -m "Update react-native-toast docs from $GITHUB_REPOSITORY@$GITHUB_SHA" || echo "No changes to commit"
          git push origin master
