name: Build and Deploy Docusaurus Site

on:
  push:
    branches: [master]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: cd website && npm install

      - name: Build Docusaurus Site
        run: cd website && npm run build

      - name: Checkout Deployment Repository
        uses: actions/checkout@v3
        with:
          repository: backpackapp-io/docs-deployment
          path: deployment-repo
          token: ${{ secrets.GIT_TOKEN }}  # The PAT with access to the deployment repo

      - name: Copy Build to Deployment Repo
        run: |
          rm -rf deployment-repo/hosting/react-native-toast
          mkdir -p deployment-repo/hosting/react-native-toast
          cp -R /website/build/* deployment-repo/hosting/react-native-toast/
        working-directory: .

      - name: Commit and Push Changes to Deployment Repo
        run: |
          cd deployment-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add hosting/react-native-toast
          git commit -m "Update react-native-toast docs from $GITHUB_REPOSITORY@$GITHUB_SHA" || echo "No changes to commit"
          git push origin main
